spring.application.name=ormLearning
spring.datasource.url = jdbc:mysql://localhost:3306/ormlearn
spring.datasource.username=root
spring.datasource.password=SAHILkv18

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

